#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

#include <ft2build.h>
#include FT_FREETYPE_H

#include "mappings.h"

#define TARGET_FONT "font/MorePerfectDOSVGA.ttf"
#define MAPPING mapping_cp437

bool setup_output_file(const char *target, FILE **fdest)
{
    FILE *f = fopen(target, "w");
    if (f == NULL)
    {
        return false;
    }
    fprintf(f, "/* File generated by ttf2c - DO NOT MODIFY MANUALLY */\n");
    fprintf(f, "#include <kernel/sysfont.h>\n\n");
    fprintf(f, "const uint16_t sysfont[] = {\n");

    *fdest = f;
    return true;
}

void finish_output_file(FILE *file)
{
    fprintf(file, "};\n");
    fclose(file);
}

void run_errors_handle(int fterr, int line)
{
    if (fterr != 0)
    {
        printf("Failure because of FreeType error %d at line %d.\n", fterr, line);
        exit(EXIT_FAILURE);
    }
}
#define ERROR_HANDLING(x) run_errors_handle(x, __LINE__)

FT_Library library;
FT_Face face;

int main(int argc, char *argv[])
{
    if (argc != 2)
    {
        printf("%s <target c file>\n", argv[0]);
        return EXIT_FAILURE;
    }
    ERROR_HANDLING(FT_Init_FreeType(&library));
    ERROR_HANDLING(FT_New_Face(library, TARGET_FONT, 0, &face));
    ERROR_HANDLING(FT_Set_Char_Size(face, 23 * 64, 23 * 64, 50, 0)); // Somehow this works, PAS TOUCHE! >:(

    FILE *f;
    if (!setup_output_file(argv[1], &f))
    {
        printf("Failed to open output file.\n");
        return EXIT_FAILURE;
    }

    FT_GlyphSlot slot = face->glyph;

    for (int n = 0; n < 256; n++)
    {
        FT_UInt glyph_index;

        glyph_index = FT_Get_Char_Index(face, MAPPING[n]);

        int error = FT_Load_Glyph(face, glyph_index, FT_LOAD_MONOCHROME);
        if (error)
            continue;

        error = FT_Render_Glyph(face->glyph, FT_RENDER_MODE_MONO);
        if (error)
            continue;
        unsigned char *ptr = slot->bitmap.buffer;
        uint16_t curr_buff = 0;
        int buff_ite = 0;

        /* We can call this the loop of the hell, it's extremely complex, but it finally works! */
        if (slot->bitmap.width > 1)
        {
            for (int y = 0; y < 16; y++)
            {
                for (int x = 0; x < 9; x++)
                {
                    if (x >= slot->bitmap_left && x < slot->bitmap_left + slot->bitmap.width && y >= (12 - slot->bitmap_top) && y < (12 - slot->bitmap_top) + slot->bitmap.rows)
                    {
                        int new_x = x - slot->bitmap_left;
                        unsigned char cur_ptr = ptr[((y - (12 - slot->bitmap_top)) * slot->bitmap.pitch) + (new_x / 8)];
                        unsigned char mask = (1 << (7 - (new_x % 8)));
                        if (((unsigned char)cur_ptr & (unsigned char)mask) != 0)
                        {
                            curr_buff |= (1 << (15 - buff_ite));
                        }
                    }

                    buff_ite++;
                    if (buff_ite >= 16)
                    {
                        buff_ite = 0;
                        fprintf(f, "%hu,", curr_buff);
                        curr_buff = 0;
                    }
                }
            }
        }
        else
        {
            fprintf(f, "0,0,0,0,0,0,0,0,0,");
        }
        fprintf(f, " // 0x%x %d \n", n, n);
    }

    fprintf(f, "};\n");
    fclose(f);

    return EXIT_SUCCESS;
}